### ISSUE TITLE
2.0 重构

### ISSUE THREAD

**Issue by Him188** [mamoe/mirai#630]
由于 mirai-core 1.0 实现有很多设计缺陷, 导致一些功能如上传文件, 上传语音等无法很好支持, 现计划 mirai-core 2.0 重构.

**此 issue 为新架构提案, 欢迎参加讨论**.

此 issue 仅包含影响架构设计的问题, 其他问题请在 [milestone](https://github.com/mamoe/mirai/milestones) 查看.

## 模块调整

- [x] 将现有 mirai-core 为 API, mirai-core-qqandroid 的模块关系调整为 mirai-core-api 为 API, mirai-core 为实现. (命名更清晰)
- [x] [在重构时实现序列化](#序列化支持), 由此去除 mirai-serialization. 

## 多平台支持

- [x] 现有 MPP 架构保留. 但目标平台确定为 JVM 和 Android JVM. 
  ```
        common(JVM)
               |
               |
         /-----+-----\
        /             \
    JVM         Android JVM
  ```
- [x] 由于 Kotlin 等级制多平台(Hierarchical Multiplatform Project, HMPP) 目前不支持多个 JVM 平台的存在, 可能要考虑生成 common JDK 桥:
  ```kotlin
  // commonMain
  package java.io
  public expect class InputStream {
      // ...
  }

  // jvmMain
  public actual typealias InputStream = java.io.InputStream
  ```

## Java 支持

- [x] 为了提供最佳的 Java 支持, 在 [kotlin-jvm-blocking-bridge](https://github.com/him188/kotlin-jvm-blocking-bridge) 的帮助下, 为所有 Kotlin `suspend` 函数添加 `@JvmBlockingBridge`.
- [x] 将所有 Kotlin 的扩展函数放置于所属类型的伴生对象下, 以允许 Java 正常调用它们.
- [x] 删除所有 `JavaFriendlyApi` 

## 协议扩展
现在所有协议实现都放置在 `Bot` 下, 这是非常糟糕的设计。

- [x] 将协议接口独立
- [ ] #563: 群列表, 好友列表刷新的公开接口
- [ ] #408: 好友列表缓存 (可选支持, 在设计刷新列表时需要考虑兼容性)

## 联系人架构
- [x] 考虑将 Contact, User, Group 等抽象类改为接口. (因为在实现它们时已经遇到了无法复用代码的问题)
- [x] 考虑兼容性 [机器人接收其他手机终端的消息](https://github.com/mamoe/mirai/issues/644)

## 序列化支持
- [x] #219: `Message` 全系支持 [kotlinx-serialization](https://github.com/Kotlin/kotlinx.serialization) 序列化

## 消息
- [x] #618, #440: `MessageSource.id` 需要修改为多个值, 以支持分片消息解析

## 事件
- [x] #514: 提供某种自动筛选监听对象 Bot 的方式
- [x] 事件系统弃用原先实现，换用JDK内置实现，可能有助于 #556 

## 代码规范
遵循 Kotlin 命名规范, 

- [x] 将 `MiraiExperimentalAPI`, `MiraiInternalAPI` 中 `API` 更名为 `Api`

## 文档
- [x] #414: 像 [mirai-console](https://github.com/mamoe/mirai-console) 一样完善文档

**Comment by Him188** [comment]
备注: 1.3 是最后一个 1.x 版本, 因为后续更新推进已经很困难 (由于设计缺陷)

**Comment by Logiase** [comment]
建议将java支持与kotlin支持分为两个模块，类似androidx库设计
以缩减包大小，减少构建时间，方便单java、单kotlin用户更加清晰的使用相关api
```
// for java 
androidx.activity:activity
// for kotlin
androidx.activity:activity-ktx
```

**Comment by Him188** [comment]
> 建议将java支持与kotlin支持分为两个模块，类似androidx库设计
> 以缩减包大小，减少构建时间，方便单java、单kotlin用户更加清晰的使用相关api
> 
> ```
> // for java 
> androidx.activity:activity
> // for kotlin
> androidx.activity:activity-ktx
> ```

Java 支持通过上述 KJBB 支持，不可能分模块实现

**Comment by Him188** [comment]
重构将在 `dev` 分支进行, 关于 1.3 版本的 patch 更新 (如果有) 会在 `1.x` 分支进行. 在 `2.0` 完成后将会保留 `1.x` 分支.

**Comment by Hieuzest** [comment]
持久化数据结构和消息存储，可选的：
- Contacts
- （minimal）Contact::lastMessageSequence
- Messages

以：

- 优化多群/好友账号的体验 #408
- 离线消息同步 #382
- 读取消息记录 #491

**Comment by Karlatemp** [comment]
event系统弃用原先使用集合，换用双向链表减小操作复杂度，可能有助于 #556

**Comment by Karlatemp** [comment]
- [ ] 将 `MiraiLogger` 中的各种扩展函数 (如 `logger.verbose {} `) 从扩展函数转成 `MiraiLogger` 的成员方法

Reason: 扩展函数中的字段名 `lazyMessage` 与扩展函数实际的操作不符, 实际运行中并不是 `lazy` 的, 移交到成员函数后也有助于对应的日志系统更好实现 `lazyMessage`

**Comment by Him188** [comment]
> * [ ]  将 `MiraiLogger` 中的各种扩展函数 (如 `logger.verbose {} `) 从扩展函数转成 `MiraiLogger` 的成员方法
> 
> Reason: 扩展函数中的字段名 `lazyMessage` 与扩展函数实际的操作不符, 实际运行中并不是 `lazy` 的, 移交到成员函数后也有助于对应的日志系统更好实现 `lazyMessage`

移动为成员函数后就不能 `inline`

**Comment by gitlsl** [comment]
http api 自动生成 swagger 文档,  方便其他语言调用, 已经有现成工具直接从 swagger文档生成各种语言的调用

**Comment by Him188** [comment]
> http api 自动生成 swagger 文档, 方便其他语言调用, 已经有现成工具直接从 swagger文档生成各种语言的调用

 无关http 与 core

**Comment by gitlsl** [comment]
> > http api 自动生成 swagger 文档, 方便其他语言调用, 已经有现成工具直接从 swagger文档生成各种语言的调用
> 
> http 与 core 无关

我理解的..  只是你 core重构了,  api 也顺带重构下,  建议直接只做 http(websocket)的api, 各语言sdk基于他做开发

**Comment by Him188** [comment]
- [ ] 考虑兼容性 [机器人接收其他手机终端的消息](https://github.com/mamoe/mirai/issues/644)

**Comment by sandtechnology** [comment]
关于 #644：其实有一种简单的兼容方式，提供一个新事件继承*MessageEvent，然后前缀加个Bot，并在事件内添加一个新属性`source`，标识来源是本机还是其他客户端即可。

**Comment by ererermao** [comment]
想请问一下，2.0是否有支持群文件的计划？

**Comment by Him188** [comment]
> 想请问一下，2.0是否有支持群文件的计划？

2.0 第一个版本是重构, 之后才会有机会支持

**Comment by landall** [comment]
是不是先集中实现单Bot比较好，多Bot管理等后续再包装。
多进程比多线程和协城要容易维护。

**Comment by Him188** [comment]
2.0 要降低实现协议的难度，并在内部实现时添加一些文档

**Comment by Him188** [comment]
此 issue 的 2.0-M1 阶段已经完成，调整到 2.0-M2
